"""okonomipost og okonomibelop

Revision ID: 4ff2c2157f1f
Revises: 2c737f92ff75
Create Date: 2014-08-13 09:56:30.504898

"""

# revision identifiers, used by Alembic.
from sqlalchemy.dialects.postgresql import ENUM

revision = '4ff2c2157f1f'
down_revision = '2c737f92ff75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('okonomi_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soknad_id', sa.Integer(), nullable=True),
    sa.Column('navn', sa.String(length=60), nullable=True),
    sa.Column('okonomipost_type', sa.Enum('Inntekt', 'Utgift', name='okonomipost_type_types'), nullable=False),
    sa.Column('okonomipost_kategori', sa.Enum('Tilskudd', 'Annet', name='okonomipost_kategori_types'), nullable=False),
    sa.ForeignKeyConstraint(['soknad_id'], ['soknader.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('okonomi_belop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('okonomipost_id', sa.Integer(), nullable=True),
    sa.Column('okonomibelop_type', sa.Enum('Budsjett', 'Regnskap', name='okonomibelop_type_types'), nullable=False),
    sa.Column('belop', sa.Integer(), nullable=True),
    sa.CheckConstraint('belop >= 0', name='chk_okonomi_belop_belop'),
    sa.ForeignKeyConstraint(['okonomipost_id'], ['okonomi_post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('okonomipost_id', 'okonomibelop_type', name='uix_okonomipost_id_okonomibelop_type')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('okonomi_belop')
    op.drop_table('okonomi_post')
    ### end Alembic commands ###
    ENUM(name="okonomipost_type_types").drop(op.get_bind(), checkfirst=False)
    ENUM(name="okonomipost_kategori_types").drop(op.get_bind(), checkfirst=False)
    ENUM(name="okonomibelop_type_types").drop(op.get_bind(), checkfirst=False)
