"""added_klage

Revision ID: 1e09c69ef6c8
Revises: 4ad6e143f70a
Create Date: 2014-10-29 10:23:31.575121

"""

# revision identifiers, used by Alembic.
revision = '1e09c69ef6c8'
down_revision = '4ad6e143f70a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('klage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soknad_id', sa.Integer(), nullable=False),
    sa.Column('vedtak_id', sa.Integer(), nullable=False),
    sa.Column('levertdato', sa.Date(), nullable=True),
    sa.Column('begrunnelse', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['soknad_id'], ['soknader.id'], ),
    sa.ForeignKeyConstraint(['vedtak_id'], ['vedtak.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('klage')
    ### end Alembic commands ###
