"""endret_behandlet_av_formannskapet

Revision ID: 12c52460b55d
Revises: 2ec6f787a011
Create Date: 2014-12-08 13:21:02.874960

"""

# revision identifiers, used by Alembic.
revision = '12c52460b55d'
down_revision = '2ec6f787a011'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vedtak', 'behandlet_av_formannskapet',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vedtak', 'behandlet_av_formannskapet',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    ### end Alembic commands ###
