"""added saksbehandler_kommentar

Revision ID: 59c403f20caa
Revises: c677948d9b0
Create Date: 2014-10-23 09:45:01.888757

"""

# revision identifiers, used by Alembic.
revision = '59c403f20caa'
down_revision = 'c677948d9b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rapport', sa.Column('saksbehandler_kommentar', sa.String(length=300), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rapport', 'saksbehandler_kommentar')
    ### end Alembic commands ###
