"""added standardtekst table

Revision ID: 1496250d15e
Revises: 50a942a618ca
Create Date: 2014-10-03 08:41:49.181717

"""

# revision identifiers, used by Alembic.
revision = '1496250d15e'
down_revision = '50a942a618ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standardtekst',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(), nullable=True),
    sa.Column('tekst', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standardtekst')
    ### end Alembic commands ###
