"""lagt til okonomipost paa rapport

Revision ID: 101b3a146ac1
Revises: 58efb81ba300
Create Date: 2014-09-15 13:30:11.150299

"""

# revision identifiers, used by Alembic.
revision = '101b3a146ac1'
down_revision = '58efb81ba300'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soknad_okonomipost',
    sa.Column('okonomipost_id', sa.Integer(), nullable=False),
    sa.Column('soknad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['okonomipost_id'], ['okonomi_post.id'], ),
    sa.ForeignKeyConstraint(['soknad_id'], ['soknader.id'], ),
    sa.PrimaryKeyConstraint('okonomipost_id', 'soknad_id')
    )
    op.create_table('rapport_okonomipost',
    sa.Column('okonomipost_id', sa.Integer(), nullable=False),
    sa.Column('rapport_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['okonomipost_id'], ['okonomi_post.id'], ),
    sa.ForeignKeyConstraint(['rapport_id'], ['rapport.id'], ),
    sa.PrimaryKeyConstraint('okonomipost_id', 'rapport_id')
    )
    op.drop_column(u'okonomi_post', 'soknad_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'okonomi_post', sa.Column('soknad_id', sa.INTEGER(), nullable=True))
    op.drop_table('rapport_okonomipost')
    op.drop_table('soknad_okonomipost')
    ### end Alembic commands ###
