"""levert dato pa soknad

Revision ID: 4018ef22f8f0
Revises: 3755365cd7d4
Create Date: 2014-09-16 14:02:00.463502

"""

# revision identifiers, used by Alembic.
revision = '4018ef22f8f0'
down_revision = '3755365cd7d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soknader', sa.Column('levert_dato', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soknader', 'levert_dato')
    ### end Alembic commands ###
