"""added_utbetaling_tabell

Revision ID: 42d910899d60
Revises: 54e8291ab376
Create Date: 2014-11-10 08:56:39.744006

"""

# revision identifiers, used by Alembic.
revision = '42d910899d60'
down_revision = '54e8291ab376'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utbetalinger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soknad_id', sa.Integer(), nullable=False),
    sa.Column('tekst', sa.String(length=15), nullable=True),
    sa.Column('utbetalt_belop', sa.Integer(), nullable=True),
    sa.Column('utbetalingsdato', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['soknad_id'], ['soknader.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utbetalinger')
    ### end Alembic commands ###
