"""added saksvedlegg table

Revision ID: 3767cae04c82
Revises: 28af58901fec
Create Date: 2014-12-02 11:08:15.745515

"""

# revision identifiers, used by Alembic.
revision = '3767cae04c82'
down_revision = '28af58901fec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saksbehandler_vedlegg',
    sa.Column('vedlegg_id', sa.Integer(), nullable=False),
    sa.Column('soknad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['soknad_id'], ['soknader.id'], ),
    sa.ForeignKeyConstraint(['vedlegg_id'], ['vedlegg.id'], ),
    sa.PrimaryKeyConstraint('vedlegg_id', 'soknad_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saksbehandler_vedlegg')
    ### end Alembic commands ###
