# -*- coding: utf-8 -*-
"""init

Revision ID: 2c737f92ff75
Revises: None
Create Date: 2014-06-25 08:28:17.622778

"""

# revision identifiers, used by Alembic.
from sqlalchemy.dialects.postgresql import ENUM

revision = '2c737f92ff75'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tilskuddsordninger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(), nullable=False),
    sa.Column('publisert', sa.Boolean(), nullable=False),
    sa.Column('forhandsutbetaling', sa.Boolean(), nullable=False),
    sa.Column('soknadsfrist', sa.Date(), nullable=False),
    sa.Column('rapportfrist', sa.Date(), nullable=True),
    sa.Column('budsjett', sa.Integer(), nullable=False),
    sa.Column('innledningstekst', sa.String(), nullable=True),
    sa.Column('prosjekttekst', sa.String(), nullable=True),
    sa.Column('budsjettekst', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uri')
    )
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uri')
    )
    op.create_table('soknader',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('tilskuddsordning_id', sa.Integer(), nullable=False),
    sa.Column('omsokt_belop', sa.Integer(), nullable=True),
    sa.Column('innstilt_belop', sa.Integer(), nullable=True),
    sa.Column('vedtatt_belop', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Kladd', 'Innlevert', 'Trukket', 'Godkjent', u'Avslått', name='soknad_status_types'), nullable=True),
    sa.Column('kontonummer', sa.String(length=11), nullable=True),
    sa.Column('epost', sa.String(length=320), nullable=True),
    sa.Column('telefon', sa.String(length=8), nullable=True),
    sa.Column('om_oss', sa.String(length=300), nullable=True),
    sa.Column('beskrivelse', sa.String(length=800), nullable=True),
    sa.Column('maalsetting', sa.String(length=300), nullable=True),
    sa.Column('prosjektnavn', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['tilskuddsordning_id'], ['tilskuddsordninger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vedlegg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soknad_id', sa.Integer(), nullable=True),
    sa.Column('navn', sa.String(), nullable=True),
    sa.Column('beskrivelse', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['soknad_id'], ['soknader.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soknad_arrangement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soknad_id', sa.Integer(), nullable=True),
    sa.Column('sted', sa.String(length=60), nullable=True),
    sa.Column('tidspunkt', sa.String(length=60), nullable=True),
    sa.Column('start_dato', sa.Date(), nullable=True),
    sa.Column('slutt_dato', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['soknad_id'], ['soknader.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soknad_arrangement')
    op.drop_table('vedlegg')
    op.drop_table('soknader')
    op.drop_table('organisations')
    op.drop_table('persons')
    op.drop_table('tilskuddsordninger')
    ### end Alembic commands ###
    ENUM(name="soknad_status_types").drop(op.get_bind(), checkfirst=False)
