"""added_merknad_paa_soknad

Revision ID: 5ab7770ab5e1
Revises: 42d910899d60
Create Date: 2014-11-12 08:34:35.107372

"""

# revision identifiers, used by Alembic.
revision = '5ab7770ab5e1'
down_revision = '42d910899d60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soknader', sa.Column('merknad', sa.String(length=150), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soknader', 'merknad')
    ### end Alembic commands ###
