"""changed_tilskuddordning_type

Revision ID: 49632d1c8552
Revises: 4daefe401b0f
Create Date: 2014-11-24 16:22:27.435298

"""

# revision identifiers, used by Alembic.
from sqlalchemy.dialects.postgresql import ENUM

revision = '49632d1c8552'
down_revision = '55e62269c95c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    tilskuddsordning_types_enum = sa.Enum('Forskuddsutbetaling',
                              'Etterskuddsutbetaling',
                              'Krever ikke rapport', name='tilskuddsordning_types')
    tilskuddsordning_types_enum.create(op.get_bind())


    op.add_column('tilskuddsordninger', sa.Column('type', tilskuddsordning_types_enum, nullable=True))
    op.drop_column('tilskuddsordninger', 'forhandsutbetaling')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tilskuddsordninger', sa.Column('forhandsutbetaling', sa.BOOLEAN(), nullable=False))
    op.drop_column('tilskuddsordninger', 'type')
    ENUM(name="tilskuddsordning_types").drop(op.get_bind(), checkfirst=False)
    ### end Alembic commands ###
