"""added_behandlet_av_formannskapet

Revision ID: 453f3f2f2e5b
Revises: 49632d1c8552
Create Date: 2014-11-27 13:53:17.778508

"""

# revision identifiers, used by Alembic.
revision = '453f3f2f2e5b'
down_revision = '49632d1c8552'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vedtak', sa.Column('behandlet_av_formannskapet', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vedtak', 'behandlet_av_formannskapet')
    ### end Alembic commands ###
