"""made_levertdato_paa_klage_mandatory

Revision ID: 3c4fb7864411
Revises: 1e09c69ef6c8
Create Date: 2014-11-03 15:44:16.035108

"""

# revision identifiers, used by Alembic.
revision = '3c4fb7864411'
down_revision = '1e09c69ef6c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('klage', 'levertdato',
               existing_type=sa.DATE(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('klage', 'levertdato',
               existing_type=sa.DATE(),
               nullable=True)
    ### end Alembic commands ###
