"""unik_navn_paa_stdtekst

Revision ID: 335fdbc76f5f
Revises: 1496250d15e
Create Date: 2014-10-08 10:36:54.355451

"""

# revision identifiers, used by Alembic.
revision = '335fdbc76f5f'
down_revision = '1496250d15e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'standardtekst', ['navn'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'standardtekst')
    ### end Alembic commands ###
