"""lagt_saksbehandler_og_godkjenner_paa_tilskuddsordn

Revision ID: 1e283f984839
Revises: 335fdbc76f5f
Create Date: 2014-10-09 12:46:59.592904

"""

# revision identifiers, used by Alembic.
revision = '1e283f984839'
down_revision = '335fdbc76f5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tilskuddsordning_saksbehandler',
    sa.Column('tilskuddsordning_id', sa.Integer(), nullable=False),
    sa.Column('saksbehandler_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tilskuddsordning_id'], ['tilskuddsordninger.id'], ),
    sa.PrimaryKeyConstraint('tilskuddsordning_id', 'saksbehandler_id')
    )
    op.add_column(u'tilskuddsordninger', sa.Column('godkjenner_id', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'tilskuddsordninger', 'godkjenner_id')
    op.drop_table('tilskuddsordning_saksbehandler')
    ### end Alembic commands ###
