"""renamed_saksbehandler_vedlegg

Revision ID: 36b9ad9003f6
Revises: 12c52460b55d
Create Date: 2014-12-08 13:22:23.002206

"""

# revision identifiers, used by Alembic.
revision = '36b9ad9003f6'
down_revision = '12c52460b55d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saks_vedlegg',
    sa.Column('vedlegg_id', sa.Integer(), nullable=False),
    sa.Column('soknad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['soknad_id'], ['soknader.id'], ),
    sa.ForeignKeyConstraint(['vedlegg_id'], ['vedlegg.id'], ),
    sa.PrimaryKeyConstraint('vedlegg_id', 'soknad_id')
    )
    op.drop_table('saksbehandler_vedlegg')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saksbehandler_vedlegg',
    sa.Column('vedlegg_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('soknad_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['soknad_id'], [u'soknader.id'], name=u'saksbehandler_vedlegg_soknad_id_fkey'),
    sa.ForeignKeyConstraint(['vedlegg_id'], [u'vedlegg.id'], name=u'saksbehandler_vedlegg_vedlegg_id_fkey'),
    sa.PrimaryKeyConstraint('vedlegg_id', 'soknad_id', name=u'saksbehandler_vedlegg_pkey')
    )
    op.drop_table('saks_vedlegg')
    ### end Alembic commands ###
