"""vedtakstabell

Revision ID: c677948d9b0
Revises: 1e283f984839
Create Date: 2014-10-10 09:32:12.990023

"""

# revision identifiers, used by Alembic.
revision = 'c677948d9b0'
down_revision = '1e283f984839'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vedtak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soknad_id', sa.Integer(), nullable=False),
    sa.Column('innstilt_belop', sa.Integer(), nullable=True),
    sa.Column('vedtatt_belop', sa.Integer(), nullable=True),
    sa.Column('intern_merknad', sa.String(length=300), nullable=True),
    sa.Column('vedtaksdato', sa.DateTime(), nullable=True),
    sa.Column('vedtakstekst', sa.String(length=800), nullable=True),
    sa.Column('rapportfrist', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['soknad_id'], ['soknader.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'soknader', 'vedtatt_belop')
    op.drop_column(u'soknader', 'innstilt_belop')
    op.drop_column(u'soknader', 'rapportfrist')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'soknader', sa.Column('innstilt_belop', sa.INTEGER(), nullable=True))
    op.add_column(u'soknader', sa.Column('vedtatt_belop', sa.INTEGER(), nullable=True))
    op.add_column(u'soknader', sa.Column('rapportfrist', sa.Date(), nullable=True))
    op.drop_table('vedtak')
    ### end Alembic commands ###
