"""dato for purring

Revision ID: 55e62269c95c
Revises: 77696845676
Create Date: 2014-11-24 11:16:09.102079

"""

# revision identifiers, used by Alembic.
revision = '55e62269c95c'
down_revision = '4daefe401b0f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vedtak', sa.Column('purret_dato', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vedtak', 'purret_dato')
    ### end Alembic commands ###
