"""changed_name_of_saksvedlegg_table

Revision ID: 2eddfabcc45d
Revises: 36b9ad9003f6
Create Date: 2014-12-09 17:12:48.683446

"""

# revision identifiers, used by Alembic.
revision = '2eddfabcc45d'
down_revision = 'f7bc7287d91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soknad_saksvedlegg',
    sa.Column('vedlegg_id', sa.Integer(), nullable=False),
    sa.Column('soknad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['soknad_id'], ['soknader.id'], ),
    sa.ForeignKeyConstraint(['vedlegg_id'], ['vedlegg.id'], ),
    sa.PrimaryKeyConstraint('vedlegg_id', 'soknad_id')
    )
    op.drop_table('saks_vedlegg')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saks_vedlegg',
    sa.Column('vedlegg_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('soknad_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['soknad_id'], [u'soknader.id'], name=u'saks_vedlegg_soknad_id_fkey'),
    sa.ForeignKeyConstraint(['vedlegg_id'], [u'vedlegg.id'], name=u'saks_vedlegg_vedlegg_id_fkey'),
    sa.PrimaryKeyConstraint('vedlegg_id', 'soknad_id', name=u'saks_vedlegg_pkey')
    )
    op.drop_table('soknad_saksvedlegg')
    ### end Alembic commands ###
