"""lagt til trukket kommentar

Revision ID: 34bd042a40a7
Revises: 5ae3e1804a54
Create Date: 2014-09-05 13:58:56.140442

"""

# revision identifiers, used by Alembic.
revision = '34bd042a40a7'
down_revision = '5ae3e1804a54'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soknader', sa.Column('trukket_kommentar', sa.String(length=700), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soknader', 'trukket_kommentar')
    ### end Alembic commands ###
