"""lagt til Vedlagtlink tabell, endret Vedlegg tabellen

Revision ID: 31679773865a
Revises: 3467d858fd
Create Date: 2014-08-29 09:49:02.952544

"""

# revision identifiers, used by Alembic.
revision = '31679773865a'
down_revision = '3467d858fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vedlagtlink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soknad_id', sa.Integer(), nullable=True),
    sa.Column('navn', sa.String(), nullable=True),
    sa.Column('beskrivelse', sa.String(), nullable=True),
    sa.Column('passord', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['soknad_id'], ['soknader.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'vedlegg', sa.Column('file_ref', sa.String(), nullable=True))
    op.add_column(u'vedlegg', sa.Column('filnavn', sa.String(), nullable=True))
    op.drop_column(u'vedlegg', 'navn')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'vedlegg', sa.Column('navn', sa.VARCHAR(), nullable=True))
    op.drop_column(u'vedlegg', 'filnavn')
    op.drop_column(u'vedlegg', 'file_ref')
    op.drop_table('vedlagtlink')
    ### end Alembic commands ###
