"""add kommentar column

Revision ID: 3467d858fd
Revises: 4ff2c2157f1f
Create Date: 2014-08-25 10:44:53.617976

"""

# revision identifiers, used by Alembic.
revision = '3467d858fd'
down_revision = '4ff2c2157f1f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soknader', sa.Column('kommentar', sa.String(length=700), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soknader', 'kommentar')
    ### end Alembic commands ###
