"""lagt_til_tittel_for_godkjenner

Revision ID: 3bb6a9c8e275
Revises: 5a061c2b26e7
Create Date: 2015-09-10 14:23:19.781215

"""

# revision identifiers, used by Alembic.
revision = '3bb6a9c8e275'
down_revision = '262da6186028'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tilskuddsordninger', sa.Column('godkjenner_tittel', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tilskuddsordninger', 'godkjenner_tittel')
    ### end Alembic commands ###
