"""empty message

Revision ID: 4bb0faf5d52
Revises: 424bd0bbccfa
Create Date: 2015-09-23 08:23:25.622109

"""

# revision identifiers, used by Alembic.
revision = '4bb0faf5d52'
down_revision = '424bd0bbccfa'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vedtak', 'vedtakstekst', type_=sa.String(length=1000))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vedtak', 'vedtakstekst', type_=sa.String(length=800))
    ### end Alembic commands ###
