"""added type to vedtak

Revision ID: 262da6186028
Revises: 5a061c2b26e7
Create Date: 2015-09-10 14:26:15.040465

"""

# revision identifiers, used by Alembic.

revision = '262da6186028'
down_revision = '5a061c2b26e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vedtak', sa.Column('tilskuddsordning_type', sa.Enum('Forskuddsutbetaling', 'Etterskuddsutbetaling', 'Krever ikke rapport', name='tilskuddsordning_types'), nullable=True))

    op.execute("update vedtak set tilskuddsordning_type = (select type from tilskuddsordninger, soknader where tilskuddsordninger.id = soknader.tilskuddsordning_id and soknader.id = vedtak.soknad_id)")
    op.alter_column('vedtak', 'tilskuddsordning_type',
                    existing_type=sa.Enum('Forskuddsutbetaling', 'Etterskuddsutbetaling', 'Krever ikke rapport', name='tilskuddsordning_types'),
                    nullable=False)


    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vedtak', 'tilskuddsordning_type')
    ### end Alembic commands ###
