"""rapport purret dato

Revision ID: 4d76a1567fe8
Revises: 2a2a61dd26dc
Create Date: 2015-01-16 10:33:55.678888

"""

# revision identifiers, used by Alembic.
revision = '4d76a1567fe8'
down_revision = '2a2a61dd26dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vedtak', sa.Column('rapport_purret_dato', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vedtak', 'rapport_purret_dato')
    ### end Alembic commands ###
