"""empty message

Revision ID: 424bd0bbccfa
Revises: df2bf3734af
Create Date: 2015-09-15 16:43:07.880216

"""

# revision identifiers, used by Alembic.
revision = '424bd0bbccfa'
down_revision = 'df2bf3734af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vedtak', sa.Column('andre_opplysninger', sa.String(length=1000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vedtak', 'andre_opplysninger')
    ### end Alembic commands ###
