"""lagt_til_lenke_til_retningslinjer

Revision ID: 5a061c2b26e7
Revises: 4d76a1567fe8
Create Date: 2015-09-08 14:35:07.585394

"""

# revision identifiers, used by Alembic.
revision = '5a061c2b26e7'
down_revision = '4d76a1567fe8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tilskuddsordninger', sa.Column('lenke_til_retningslinjer', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tilskuddsordninger', 'lenke_til_retningslinjer')
    ### end Alembic commands ###
