"""add column avskrevet_rapportkrav_kommentar

Revision ID: 23adc825714b
Revises: 4bb0faf5d52
Create Date: 2015-09-29 07:33:26.377207

"""

# revision identifiers, used by Alembic.
revision = '23adc825714b'
down_revision = '4bb0faf5d52'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soknader', sa.Column('avskrevet_rapportkrav_kommentar', sa.String(length=700), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soknader', 'avskrevet_rapportkrav_kommentar')
    ### end Alembic commands ###
