"""endre_lengde_paa_intern_merknad

Revision ID: 140475cd6c7
Revises: 2816c7504f15
Create Date: 2016-02-11 22:35:32.858897

"""

# revision identifiers, used by Alembic.
revision = '140475cd6c7'
down_revision = '2816c7504f15'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vedtak', 'intern_merknad', type_=sa.String(length=600))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vedtak', 'intern_merknad', type_=sa.String(length=300))
    ### end Alembic commands ###
