"""endre_lengde_paa_m

Revision ID: 2816c7504f15
Revises: 33a3cac025a0
Create Date: 2016-02-11 22:30:48.120572

"""

# revision identifiers, used by Alembic.
revision = '2816c7504f15'
down_revision = '23adc825714b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('soknader', 'merknad', type_=sa.String(length=600))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('soknader', 'merknad', type_=sa.String(length=150))
    ### end Alembic commands ###
